/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExerciseType = IDL.Variant({
  'compound' : IDL.Null,
  'isolation' : IDL.Null,
  'cardio' : IDL.Null,
});
export const MuscleGroup = IDL.Variant({
  'shoulders' : IDL.Null,
  'arms' : IDL.Null,
  'back' : IDL.Null,
  'core' : IDL.Null,
  'chest' : IDL.Null,
  'legs' : IDL.Null,
});
export const Exercise = IDL.Record({
  'difficulty' : IDL.Nat8,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'exerciseType' : ExerciseType,
  'muscleGroup' : MuscleGroup,
});
export const Time = IDL.Int;
export const DaySummary = IDL.Record({
  'totalVolume' : IDL.Nat,
  'date' : Time,
  'workoutCount' : IDL.Nat,
});
export const WeeklySummary = IDL.Record({ 'days' : IDL.Vec(DaySummary) });
export const Set = IDL.Record({ 'weight' : IDL.Nat, 'reps' : IDL.Nat });
export const ExerciseEntry = IDL.Record({
  'exerciseId' : IDL.Nat,
  'sets' : IDL.Vec(Set),
});
export const WorkoutLog = IDL.Record({
  'date' : Time,
  'exercises' : IDL.Vec(ExerciseEntry),
});
export const WorkoutPlan = IDL.Record({
  'duration' : IDL.Nat,
  'exerciseIds' : IDL.Vec(IDL.Nat),
  'difficulty' : IDL.Nat8,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'getExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getExercisesByMuscleGroup' : IDL.Func(
      [MuscleGroup],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
  'getWeeklyProgress' : IDL.Func([Time], [WeeklySummary], ['query']),
  'getWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
  'getWorkoutPlanById' : IDL.Func([IDL.Nat], [WorkoutPlan], ['query']),
  'getWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
  'logWorkout' : IDL.Func([Time, IDL.Vec(ExerciseEntry)], [], []),
  'searchExercises' : IDL.Func([IDL.Text], [IDL.Vec(Exercise)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExerciseType = IDL.Variant({
    'compound' : IDL.Null,
    'isolation' : IDL.Null,
    'cardio' : IDL.Null,
  });
  const MuscleGroup = IDL.Variant({
    'shoulders' : IDL.Null,
    'arms' : IDL.Null,
    'back' : IDL.Null,
    'core' : IDL.Null,
    'chest' : IDL.Null,
    'legs' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'difficulty' : IDL.Nat8,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'exerciseType' : ExerciseType,
    'muscleGroup' : MuscleGroup,
  });
  const Time = IDL.Int;
  const DaySummary = IDL.Record({
    'totalVolume' : IDL.Nat,
    'date' : Time,
    'workoutCount' : IDL.Nat,
  });
  const WeeklySummary = IDL.Record({ 'days' : IDL.Vec(DaySummary) });
  const Set = IDL.Record({ 'weight' : IDL.Nat, 'reps' : IDL.Nat });
  const ExerciseEntry = IDL.Record({
    'exerciseId' : IDL.Nat,
    'sets' : IDL.Vec(Set),
  });
  const WorkoutLog = IDL.Record({
    'date' : Time,
    'exercises' : IDL.Vec(ExerciseEntry),
  });
  const WorkoutPlan = IDL.Record({
    'duration' : IDL.Nat,
    'exerciseIds' : IDL.Vec(IDL.Nat),
    'difficulty' : IDL.Nat8,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'getExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getExercisesByMuscleGroup' : IDL.Func(
        [MuscleGroup],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'getWeeklyProgress' : IDL.Func([Time], [WeeklySummary], ['query']),
    'getWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
    'getWorkoutPlanById' : IDL.Func([IDL.Nat], [WorkoutPlan], ['query']),
    'getWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
    'logWorkout' : IDL.Func([Time, IDL.Vec(ExerciseEntry)], [], []),
    'searchExercises' : IDL.Func([IDL.Text], [IDL.Vec(Exercise)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };