/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DaySummary {
  'totalVolume' : bigint,
  'date' : Time,
  'workoutCount' : bigint,
}
export interface Exercise {
  'difficulty' : number,
  'name' : string,
  'description' : string,
  'exerciseType' : ExerciseType,
  'muscleGroup' : MuscleGroup,
}
export interface ExerciseEntry { 'exerciseId' : bigint, 'sets' : Array<Set> }
export type ExerciseType = { 'compound' : null } |
  { 'isolation' : null } |
  { 'cardio' : null };
export type MuscleGroup = { 'shoulders' : null } |
  { 'arms' : null } |
  { 'back' : null } |
  { 'core' : null } |
  { 'chest' : null } |
  { 'legs' : null };
export interface Set { 'weight' : bigint, 'reps' : bigint }
export type Time = bigint;
export interface WeeklySummary { 'days' : Array<DaySummary> }
export interface WorkoutLog {
  'date' : Time,
  'exercises' : Array<ExerciseEntry>,
}
export interface WorkoutPlan {
  'duration' : bigint,
  'exerciseIds' : Array<bigint>,
  'difficulty' : number,
  'name' : string,
  'description' : string,
}
export interface _SERVICE {
  'getExercises' : ActorMethod<[], Array<Exercise>>,
  'getExercisesByMuscleGroup' : ActorMethod<[MuscleGroup], Array<Exercise>>,
  'getWeeklyProgress' : ActorMethod<[Time], WeeklySummary>,
  'getWorkoutLogs' : ActorMethod<[], Array<WorkoutLog>>,
  'getWorkoutPlanById' : ActorMethod<[bigint], WorkoutPlan>,
  'getWorkoutPlans' : ActorMethod<[], Array<WorkoutPlan>>,
  'logWorkout' : ActorMethod<[Time, Array<ExerciseEntry>], undefined>,
  'searchExercises' : ActorMethod<[string], Array<Exercise>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];