/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    difficulty: number;
    name: string;
    description: string;
    exerciseType: ExerciseType;
    muscleGroup: MuscleGroup;
}
export interface WorkoutPlan {
    duration: bigint;
    exerciseIds: Array<bigint>;
    difficulty: number;
    name: string;
    description: string;
}
export interface WorkoutLog {
    date: Time;
    exercises: Array<ExerciseEntry>;
}
export interface WeeklySummary {
    days: Array<DaySummary>;
}
export type Time = bigint;
export interface ExerciseEntry {
    exerciseId: bigint;
    sets: Array<Set_>;
}
export interface DaySummary {
    totalVolume: bigint;
    date: Time;
    workoutCount: bigint;
}
export interface Set_ {
    weight: bigint;
    reps: bigint;
}
export enum ExerciseType {
    compound = "compound",
    isolation = "isolation",
    cardio = "cardio"
}
export enum MuscleGroup {
    shoulders = "shoulders",
    arms = "arms",
    back = "back",
    core = "core",
    chest = "chest",
    legs = "legs"
}
export interface backendInterface {
    getExercises(): Promise<Array<Exercise>>;
    getExercisesByMuscleGroup(muscleGroup: MuscleGroup): Promise<Array<Exercise>>;
    getWeeklyProgress(weekStart: Time): Promise<WeeklySummary>;
    getWorkoutLogs(): Promise<Array<WorkoutLog>>;
    getWorkoutPlanById(id: bigint): Promise<WorkoutPlan>;
    getWorkoutPlans(): Promise<Array<WorkoutPlan>>;
    logWorkout(date: Time, exercises: Array<ExerciseEntry>): Promise<void>;
    searchExercises(searchTerm: string): Promise<Array<Exercise>>;
}
import type { Exercise as _Exercise, ExerciseType as _ExerciseType, MuscleGroup as _MuscleGroup } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercises();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercises();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExercisesByMuscleGroup(arg0: MuscleGroup): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercisesByMuscleGroup(to_candid_MuscleGroup_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercisesByMuscleGroup(to_candid_MuscleGroup_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyProgress(arg0: Time): Promise<WeeklySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyProgress(arg0);
            return result;
        }
    }
    async getWorkoutLogs(): Promise<Array<WorkoutLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutLogs();
            return result;
        }
    }
    async getWorkoutPlanById(arg0: bigint): Promise<WorkoutPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutPlanById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutPlanById(arg0);
            return result;
        }
    }
    async getWorkoutPlans(): Promise<Array<WorkoutPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutPlans();
            return result;
        }
    }
    async logWorkout(arg0: Time, arg1: Array<ExerciseEntry>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkout(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkout(arg0, arg1);
            return result;
        }
    }
    async searchExercises(arg0: string): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchExercises(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchExercises(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ExerciseType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExerciseType): ExerciseType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Exercise_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MuscleGroup_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MuscleGroup): MuscleGroup {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    difficulty: number;
    name: string;
    description: string;
    exerciseType: _ExerciseType;
    muscleGroup: _MuscleGroup;
}): {
    difficulty: number;
    name: string;
    description: string;
    exerciseType: ExerciseType;
    muscleGroup: MuscleGroup;
} {
    return {
        difficulty: value.difficulty,
        name: value.name,
        description: value.description,
        exerciseType: from_candid_ExerciseType_n4(_uploadFile, _downloadFile, value.exerciseType),
        muscleGroup: from_candid_MuscleGroup_n6(_uploadFile, _downloadFile, value.muscleGroup)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    compound: null;
} | {
    isolation: null;
} | {
    cardio: null;
}): ExerciseType {
    return "compound" in value ? ExerciseType.compound : "isolation" in value ? ExerciseType.isolation : "cardio" in value ? ExerciseType.cardio : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shoulders: null;
} | {
    arms: null;
} | {
    back: null;
} | {
    core: null;
} | {
    chest: null;
} | {
    legs: null;
}): MuscleGroup {
    return "shoulders" in value ? MuscleGroup.shoulders : "arms" in value ? MuscleGroup.arms : "back" in value ? MuscleGroup.back : "core" in value ? MuscleGroup.core : "chest" in value ? MuscleGroup.chest : "legs" in value ? MuscleGroup.legs : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n2(_uploadFile, _downloadFile, x));
}
function to_candid_MuscleGroup_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MuscleGroup): _MuscleGroup {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MuscleGroup): {
    shoulders: null;
} | {
    arms: null;
} | {
    back: null;
} | {
    core: null;
} | {
    chest: null;
} | {
    legs: null;
} {
    return value == MuscleGroup.shoulders ? {
        shoulders: null
    } : value == MuscleGroup.arms ? {
        arms: null
    } : value == MuscleGroup.back ? {
        back: null
    } : value == MuscleGroup.core ? {
        core: null
    } : value == MuscleGroup.chest ? {
        chest: null
    } : value == MuscleGroup.legs ? {
        legs: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
